app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Display all SQL executed in Eloquent 
/*Event::listen('illuminate.query', function($query)
{
    var_dump($query);
});*/

// canviar pass admin
Route::get('crearpass_admin', function()
{
    DB::table('users')
            ->where('id', 10)
            ->update(array('password' => Hash::make('UFdn24XTY')));
});



Route::get('login', 'AuthController@getLogIn');

Route::post('login', 'AuthController@postLogIn');

Route::controller('password', 'RemindersController');


//Invoice test (Rebuts)
Route::post('print/invoice/print', ['as' => 'invoice.payprintapp', 'uses' => 'InvoiceController@payprintapp']);
Route::get('print/invoice/print', ['as' => 'invoice.payprintapp', 'uses' => 'InvoiceController@payprintapp']);



Route::group(array('before' => 'auth'), function()
{
    Route::get('error', function(){
        return View::make('private.modelexception'); 
    });



    Route::get('/', 'HomeController@home');
    
    Route::get('logout', 'AuthController@postLogOut');

    Route::get('move/{id}', 'AuthController@move');

    Route::get('stall/getinfo', 'StallController@getInfo');

    Route::get('stall/ajaxSearch', 'StallController@ajaxSearch');

    Route::any('mapa', 'MapController@showMap');

    Route::post('presence/toggle', 'PresenceController@togglePresence');

    Route::post('sector/editProducts/{id}', 'SectorController@editProducts');
    Route::post('sector/deleteProducts/{id}', 'SectorController@deleteProducts');


    
    //ADMIN
    Route::group(array('before' => 'admin'), function()
    {
        Route::resource('user', 'UserController');
        Route::get('stall/{id}', 'StallController@show');
        Route::get('stall/{id}/edit', 'StallController@editStall');


        

    });
    
    // INT
    Route::group(array('before' => 'int'), function()
    {
        Route::get('ownerstall/ajaxStallSearch', 'OwnerStallController@ajaxStallSearch');
        Route::get('ownerstall/ajaxOwnerSearch', 'OwnerStallController@ajaxOwnerSearch');
        Route::resource('ownerstall', 'OwnerStallController');

        Route::resource('sector', 'SectorController');

        Route::resource('authprod', 'AuthProdController');

        Route::resource('calendar', 'CalendarController');

        Route::resource('absence', 'AbsenceController');

        Route::resource('tariff', 'TariffController');
    });
    
    // TAB
    Route::group(array('before' => 'tab'), function()
    {
        // OWNER
        Route::get('owner/ajaxSearch', 'OwnerController@ajaxSearch');
        Route::resource('owner', 'OwnerController');
        
        // STALL
/*        Route::get('stall/ajaxSearch', 'StallController@ajaxSearch2');
*/        Route::resource('stall', 'StallController');
        
        // INVOICE
        Route::get('invoice/printout/{id}', ['as' => 'invoice.printout', 'uses' => 'InvoiceController@printout']);
        Route::get('invoice/payprint/{id}', ['as' => 'invoice.payprint', 'uses' => 'InvoiceController@payprint']);
        Route::resource('invoice', 'InvoiceController');
        Route::get('invoice/printandpay/{id}',['as' => 'invoice.printandpay', 'uses' => 'InvoiceController@printandpay']);
        Route::get('notpaid', ['as' => 'invoice.notpaid', 'uses' => 'InvoiceController@indexNotPaid']);

        // PRESENCE
        Route::resource('presence', 'PresenceController');
        Route::get('presence_no',   'PresenceController@indexPresence');

        // NOTES
        Route::resource('notes', 'NotesController');

        // AUTHPROD
        Route::get('authprod/sector/{id}',['as' => 'authprod.showsector', 'uses' => 'AuthProdController@relation_sector_products']);

    });

    
    
});

app/models/Stall.php
<?php

class Stall extends Eloquent
{

    protected $table = 'stall';
    protected $fillable = array('num', 'lenght');

    public function market()
    {
        return $this->belongsTo('Market');
    }
    
    public function sector()
    {
        return $this->belongsTo('Sector');
    }
    
    public function authprod()
    {
        return $this->belongsTo('AuthProd', 'auth_prod_id');
    }
    
    public function owners()
    {
        return $this->belongsToMany('Owner', 'ownerstall')
            ->withPivot('id', 'insurance', 'discharge_date', 'expire_date', 'deactivated_at', 'created_at')
            ->orderBy('deactivated_at', 'asc');
    }
    
    public function activeOwner()
    {
        return $this->belongsToMany('Owner', 'ownerstall')
            ->withPivot('id', 'insurance', 'discharge_date', 'expire_date', 'deactivated_at', 'created_at')
            ->where('deactivated_at', '=', null);
    }
    
    public function inactiveOwners()
    {
        return $this->belongsToMany('Owner', 'ownerstall')
            ->withPivot('id', 'insurance', 'discharge_date', 'expire_date', 'deactivated_at', 'created_at')
            ->where('deactivated_at', '!=', null);
    }


    public function absences()
    {
        return $this->HasMany('Absence', 'ownerstall_id', 'num');
    }
}

app/controllers/StallController.php
<?php

class StallController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $stalls = Stall::where('market_id', '=', Session::get('market'))
                ->with('authprod', 'sector', 'activeOwner')
                ->get();

        return View::make('private.stall.index')
                        ->with('stalls', $stalls);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $stall = Stall::where('id', '=', $id)
                ->where('market_id', '=', Session::get('market'))
                ->firstOrFail();

        $ownerstall = OwnerStall::where('stall_id', '=', $id)
                ->whereHas('stall', function($q)
                {
                    $q->where('market_id', Session::get('market'));
                })
                ->get();

        $presence = Presence::whereHas('ownerstall', function ($q) use($id)
                {
                    $q->whereHas('stall', function($q) use($id)
                    {
                        $q->where('market_id', Session::get('market'));
                    })
                    ->where('stall_id', $id);
                })
                ->with('ownerstall', 'ownerstall.stall', 'calendar')
                ->get();

        $notes = Note::whereHas('ownerstall', function ($q) use($id)
                {
                    $q->where('stall_id', $id);
                })
                ->where('market_id', Session::get('market'))
                ->with('ownerstall', 'ownerstall.stall')
                ->get();
        
        $general = Note::whereNull('ownerstall_id')
                ->where('market_id', Session::get('market'))
                ->with('ownerstall', 'ownerstall.stall')
                ->get();

        $absence = Absence::whereHas('ownerstall', function ($q) use($id)
                {
                    $q->whereHas('stall', function($q) use($id)
                    {
                        $q->where('market_id', Session::get('market'));
                    })
                    ->where('stall_id', $id);
                })
                ->with('ownerstall', 'ownerstall.stall')
                ->get();

        $invoices = Invoice::whereHas('OwnerStall', function($q) use($id)
                {
                    $q->whereHas('stall', function($q)
                    {
                        $q->where('market_id', Session::get('market'));
                    })
                    ->where('stall_id', $id);
                })
                ->with('ownerstall', 'ownerstall.owner', 'ownerstall.stall')
                ->get();

        return View::make('private.stall.show')
                        ->with('stall', $stall)
                        ->with('ownerstalls', $ownerstall)
                        ->with('presence', $presence)
                        ->with('notes', $notes)
                        ->with('general', $general)
                        ->with('absences', $absence)
                        ->with('invoices', $invoices);
    }

    /**
    * Display info.
    *
    * @param  int  $id
    * @return Response
    */
    public function getInfo(){

        if(Input::has('market')){
            $market_id = Input::get('market');
            Session::put('market', $market_id);
        }else{
            $market_id = Session::get('market');
        }

        $response['market_id'] = $market_id;
        $response['num'] = Input::get('num');

        $stall = Stall::where('market_id', $market_id)
                    ->where('num', Input::get('num'))
                    ->orderBy('id', 'asc')
                    ->firstOrFail();
                
        $route = 'stall/' . $stall->id;
        return Redirect::to($route);
    }


    /**
    * Display info.
    *
    * @param  int  $id
    * @return Response
    */
    public function editStall($id){

        $stall = Stall::where('id', '=', $id)
                ->where('market_id', '=', Session::get('market'))
                ->firstOrFail();

                dd($stall);

        return View::make('private.stall.edit')
                        ->with('stall', $stall);
    }

    
    /**
    * Ajax search
    *
    * @return json
    */
    public function ajaxSearch()
    {
        $stalls = Stall::has('activeOwner', 0)
                ->where('market_id', Session::get('market'))
                ->where('num', 'like', '%' . Input::get('term') . '%')
                ->with('sector')
                ->with('authprod')
                ->get();
                        
        return Response::json($stalls);
    }

}

app/views/private/stall/index.blade.php
@include('private.header')

{{ HTML::style('assets/datatables/media/css/dataTables.bootstrap.css'); }}
{{ HTML::style('assets/datepicker/dist/css/bootstrap-datepicker.css') }}
{{ HTML::style('assets/datatables/extensions/TableTools/css/dataTables.tableTools.min.css'); }}


<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                Parades
            </div>
            <div class="col-md-4 text-right">
                <a href="{{ URL::route('ownerstall.create') }}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Assignar parada
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        @include('private.success')

        @if ($stalls->isEmpty())
        <div class="alert alert-info text-center" role="alert">
            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
            No hi ha parades
        </div>
        @else
        <table id="datatable" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Parada</th>
                    <th class="text-right">Metres</th>
                    <th>Producte</th>
                    <th>Sector</th>
                    <th>Titular</th>
                    <th>Alta</th>
                    <th>Caducitat</th>
                    <th class="text-center">Activa</th>
                    <th class="text-center">Opcions</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                <tr>
                    <td id="col-0"></td>
                    <td id="col-1" class="text-center"></td>
                    <td id="col-2"></td>
                    <td id="col-3" ></td>
                    <td id="col-4"></td>
                    <td id="col-5"></td>
                    <td id="col-6"></td>
                    <td id="col-7" class="text-center"></td>
                    <td id="col-8"></td>
                </tr>
            </tfoot>
            @foreach ($stalls as $value)
            <tr> 
                <td><a href="{{ URL::route('stall.show', $value->id) }}">{{$value->num}}</a></td>
                <td class="text-right">{{$value->length}}</td>
                <td>{{$value->authprod->name}}</td>
                <td>{{$value->sector->name}}</td>
                @if ($value->activeOwner->isEmpty())
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="text-center warning">No</td>
                    <td class="text-center">
                        <a class='btn btn-xs btn-default ttip' data-toggle="tooltip" data-placement="top" title="Assignar titular" href="{{ URL::route('ownerstall.create', ['stall_id' => $value->id]) }}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </td>
                @else
                    <?php $activeOwner = $value->activeOwner->first(); ?>
                    <td><a href="{{ URL::route('owner.show', $activeOwner->id) }}">{{$activeOwner->dni}} {{$activeOwner->name}}</a></td>
                    <td>{{date('d/m/Y', strtotime($activeOwner->pivot->discharge_date))}}</td>
                    <td>{{date('d/m/Y', strtotime($activeOwner->pivot->expire_date))}}</td>
                    
                    <td class="text-center success">Si</td>
                    <td class="text-center">
                        {{ Form::open(array('url' => "ownerstall/{$activeOwner->pivot->id}")) }}
                        <a class='btn btn-default btn-xs ttip' data-toggle="tooltip" data-placement="top" title="Editar dates" href="{{ URL::route('ownerstall.edit', $activeOwner->pivot->id) }}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>
                        {{ Form::hidden('_method', 'DELETE') }}

                        <? $date_now = date('Y-m-d H:i:s'); ?>
                        <!-- Modal -->
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Donar de Baixa</h4>
                              </div>
                              <div class="modal-body">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">Data de baixa</label>
                                        <div class="col-sm-9">
                                            {{ Form::input('date', 'deactivated_at', date('Y-m-d', strtotime($date_now)), Array('class' => 'form-control')) }}
                                        </div>
                                    </div>
                              </div>
                              <div class="modal-footer">
                                <div class="text-right">
                                    <a data-dismiss="modal" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel·lar</a>
                                    {{ Form::button('<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Donar de Baixa', ['class'=>'btn btn-danger', 'title'=>"Donar de baixa", 'type'=>'submit']) }}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <!-- Modal -->

                        {{ Form::button('<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>', ['class'=>'btn  btn-xs btn-danger confirm ttip', 'data-toggle'=>"tooltip", 'data-placement'=>"top", 'title'=>"Donar de baixa", 'data-toggle'=>"modal" , 'data-target'=>"#myModal"]) }}
                        {{ Form::close() }}
                    </td>
                @endif
            </tr>
            @endforeach
        </table>
        @endif
    </div>
</div>

@include('private.footer')

{{ HTML::script('assets/datepicker/js/bootstrap-datepicker.js') }}
{{ HTML::script('assets/datepicker/dist/locales/bootstrap-datepicker.es.min.js') }}
{{ HTML::script('assets/moment.min.js')}}

{{ HTML::script('assets/datatables/media/js/jquery.dataTables.js'); }}
{{ HTML::script('assets/datatables/media/js/dataTables.bootstrap.js'); }}
{{ HTML::script('assets/datatables/media/js/Spanish.js'); }}
{{ HTML::script('assets/datatables/extensions/dataTables.tableTools.min.js')}}

<script>
    $('.confirm').click(function () {
        if (confirm("Desitja donar de baixa el titular?") === false)
        {
            event.preventDefault();
            return false;
        }
    });

    function count(api, column, type)
    {
        var result = {active: 0, inactive: 0};

        api.column(column, type).data().each(function (v) {
            if (v == 'Si')
                result.active += 1;
            else if (v == 'No')
                result.inactive += 1;
        });
        return result;
    }
    
    function sum(api, column, search, type)
    {
        var result = {active: 0.0, inactive: 0.0};

        var column = api.column(column, type).data();
        var search = api.column(search, type).data();
        
        column.each(function(v, k){
            if (search[k] == 'Si')
                result.active += parseFloat(v);
            else if (search[k] == 'No')
                result.inactive += parseFloat(v);
        });
        return result;
    }
    
    $('#datatable tfoot th').each(function () {
        var title = $('#datatable thead th').eq($(this).index()).text();
        $(this).html('<input id="'+title+'"type="text" class="form-control" placeholder="' + title + '" />');
    });

    $(document).ready(function () {

        $('#Caducitat').datepicker({
            format: 'dd/mm/yyyy',
            language: "es",
            weekStart: 1,
            orientation: 'top auto',
            changeMonth: true,
            changeYear: false
        });


        $('#Alta').datepicker({
            format: 'dd/mm/yyyy',
            language: "es",
            weekStart: 1,
            orientation: 'top auto',
            changeMonth: true,
            changeYear: false
        });


        
        var table = $('#datatable').DataTable({
            dom: 'lTfrtip',
            language: spanish,
            tableTools: {
                    sSwfPath: "{{ URL::asset('assets/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf') }}",
                    aButtons: [
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'print',
                            sButtonText: 'Imprimir',
                            sInfo: "<h4>Utilitzi el menú de l'explorador per imprimir la página</h4>Premi [Esc] per sortir"
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'xls',
                            sFileName: "*.xls",
                            sButtonText: 'XLS'
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'csv',
                            sButtonText: 'CSV'
                        }
                    ]
            },
            columnDefs: [{orderable: false, targets: [8]}],
            footerCallback: function (row, data, start, end, display) {

                var api = this.api(), data;

                //var total = count(api, 7, {});
                //var current = count(api, 7, {page: 'current'});
                var filter = count(api, 7, {filter: 'applied'});

                $('#col-7').html(
//                        'Si (pagina): ' + current.active + '<br>' +
                        'Si: ' + filter.active + '<br>' +
//                        'Si (total): ' + total.active + '<hr>' +
//                        'No (pagina): ' + current.inactive + '<br>' +
                        'No: ' + filter.inactive + '<br>'
//                        + 'No (totals): ' + total.inactive + '<hr>'
                        );
                
                //var total = sum(api, 1, 7, {});
                //var current = sum(api, 1, 7, {page: 'current'});
                var filter = sum(api, 1, 7, {filter: 'applied'});
                
                $('#col-1').html(
//                        'Si (pagina): ' + current.active + 'm<br>' +
                        'Actius: ' + filter.active + 'm<br>' +
//                        'Si (total): ' + total.active + 'm<hr>' +
//                        'No (pagina): ' + current.inactive + 'm<br>' +
                        'Inactius: ' + filter.inactive + 'm<br>'
//                         +'No (totals): ' + total.inactive + 'm<hr>'
                );

            }
        });
        
        // Apply the search
        table.columns().eq(0).each(function (colIdx) {
            $('input', table.column(colIdx).footer()).on('keyup change', function () {
                table
                        .column(colIdx)
                        .search(this.value)
                        .draw();
            });
        });
    });
</script>