app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Display all SQL executed in Eloquent 
/*Event::listen('illuminate.query', function($query)
{
    var_dump($query);
});*/

// canviar pass admin
Route::get('crearpass_admin', function()
{
    DB::table('users')
            ->where('id', 10)
            ->update(array('password' => Hash::make('UFdn24XTY')));
});



Route::get('login', 'AuthController@getLogIn');

Route::post('login', 'AuthController@postLogIn');

Route::controller('password', 'RemindersController');


//Invoice test (Rebuts)
Route::post('print/invoice/print', ['as' => 'invoice.payprintapp', 'uses' => 'InvoiceController@payprintapp']);
Route::get('print/invoice/print', ['as' => 'invoice.payprintapp', 'uses' => 'InvoiceController@payprintapp']);



Route::group(array('before' => 'auth'), function()
{
    Route::get('error', function(){
        return View::make('private.modelexception'); 
    });



    Route::get('/', 'HomeController@home');
    
    Route::get('logout', 'AuthController@postLogOut');

    Route::get('move/{id}', 'AuthController@move');

    Route::get('stall/getinfo', 'StallController@getInfo');

    Route::get('stall/ajaxSearch', 'StallController@ajaxSearch');

    Route::any('mapa', 'MapController@showMap');

    Route::post('presence/toggle', 'PresenceController@togglePresence');

    Route::post('sector/editProducts/{id}', 'SectorController@editProducts');
    Route::post('sector/deleteProducts/{id}', 'SectorController@deleteProducts');


    
    //ADMIN
    Route::group(array('before' => 'admin'), function()
    {
        Route::resource('user', 'UserController');
        Route::get('stall/{id}', 'StallController@show');
        Route::get('stall/{id}/edit', 'StallController@editStall');


        

    });
    
    // INT
    Route::group(array('before' => 'int'), function()
    {
        Route::get('ownerstall/ajaxStallSearch', 'OwnerStallController@ajaxStallSearch');
        Route::get('ownerstall/ajaxOwnerSearch', 'OwnerStallController@ajaxOwnerSearch');
        Route::resource('ownerstall', 'OwnerStallController');

        Route::resource('sector', 'SectorController');

        Route::resource('authprod', 'AuthProdController');

        Route::resource('calendar', 'CalendarController');

        Route::resource('absence', 'AbsenceController');

        Route::resource('tariff', 'TariffController');
    });
    
    // TAB
    Route::group(array('before' => 'tab'), function()
    {
        // OWNER
        Route::get('owner/ajaxSearch', 'OwnerController@ajaxSearch');
        Route::resource('owner', 'OwnerController');
        
        // STALL
/*        Route::get('stall/ajaxSearch', 'StallController@ajaxSearch2');
*/        Route::resource('stall', 'StallController');
        
        // INVOICE
        Route::get('invoice/printout/{id}', ['as' => 'invoice.printout', 'uses' => 'InvoiceController@printout']);
        Route::get('invoice/payprint/{id}', ['as' => 'invoice.payprint', 'uses' => 'InvoiceController@payprint']);
        Route::resource('invoice', 'InvoiceController');
        Route::get('invoice/printandpay/{id}',['as' => 'invoice.printandpay', 'uses' => 'InvoiceController@printandpay']);
        Route::get('notpaid', ['as' => 'invoice.notpaid', 'uses' => 'InvoiceController@indexNotPaid']);

        // PRESENCE
        Route::resource('presence', 'PresenceController');
        Route::get('presence_no',   'PresenceController@indexPresence');

        // NOTES
        Route::resource('notes', 'NotesController');

        // AUTHPROD
        Route::get('authprod/sector/{id}',['as' => 'authprod.showsector', 'uses' => 'AuthProdController@relation_sector_products']);

    });

    
    
});

app/models/Owner.php
<?php

class Owner extends Eloquent
{

    protected $table = 'owner';
    protected $fillable = array('name', 'address', 'email', 'dni', 'phone', 'iban', 'sname', 'saddress', 'semail', 'sdni', 'sphone');

    
    public function stalls()
    {
        return $this->belongsToMany('Stall', 'ownerstall')
            ->withPivot('insurance', 'discharge_date', 'expire_date', 'deactivated_at', 'created_at')
            ->where('market_id', '=', Session::get('market'));
    }
    
    public function activeStalls()
    {
        return $this->belongsToMany('Stall', 'ownerstall')
            ->withPivot('insurance', 'discharge_date', 'expire_date', 'deactivated_at', 'created_at')
            ->where('market_id', '=', Session::get('market'))
            ->whereNull('deactivated_at');
    }
    
}

app/controllers/OwnerController.php
<?php

class OwnerController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //$owners = Owner::has('stalls')->get();
        $owners = Owner::get();

        return View::make('private.owner.index')
                        ->with('owners', $owners);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('private.owner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $inputs = Input::all();
        
        $nice = ['name' => 'nom',
                'address' => 'direcció',
                'email' => 'correu electrònic',
                'dni' => 'dni',
                'phone' => 'telèfon',
                'iban' => 'iban',
                'image' => 'foto',
                'pdf1' => 'Alta AIE',
                'pdf2' => 'Alta autònoms',
                'sname' => 'nom del suplent',
                'saddress' => 'direcció del suplent',
                'semail' => 'correu del suplent',
                'sdni' => 'dni del suplent',
                'sphone' => 'teléfon del suplent',
                'pdf3' => 'contracte de treball'];
        
        $rules = [ 'name' => 'required|between:1,100',
            'address' => 'required|between:1,500',
            'email' => 'email|unique:owner,email|between:1,100',
            'dni' => 'required|unique:owner,dni|between:9,9',
            'phone' => 'required|digits_between:9,9',
            'iban' => 'required', //think about check it
            'image' => 'image',
            'pdf1' => 'mimes:pdf',
            'pdf2' => 'mimes:pdf',
            'sname' => 'between:1,100',
            'saddress' => 'between:1,500',
            'semail' => 'email|between:1,100',
            'sdni' => 'between:9,9',
            'sphone' => 'digits_between:9,9',
            'pdf3' => 'mimes:pdf'];

        $validation = Validator::make($inputs, $rules);
        $validation->setAttributeNames($nice);


        if ($validation->fails())
        {
            return Redirect::route('owner.create')
                            ->withErrors($validation)
                            ->withInput();
        }
        else
        {
            $owner = new Owner(Input::all());

            if (Input::hasFile('image') && Input::file('image')->isValid())
            {
                $file = Input::file('image');
                $owner->image = strtolower('user-' . date('ymdhis') . '-' . $file->getClientOriginalName());
                $file->move("imgs", $owner->image);
            }
            
            if (Input::hasFile('pdf1') && Input::file('pdf1')->isValid())
            {
                $file = Input::file('pdf1');
                $owner->pdf1 = strtolower('pdf1-' . date('ymdhis') . '-' . $file->getClientOriginalName());
                $file->move("pdf", $owner->pdf1);
            }
            
            if (Input::hasFile('pdf2') && Input::file('pdf2')->isValid())
            {
                $file = Input::file('pdf2');
                $owner->pdf2 = strtolower('pdf2-' . date('ymdhis') . '-' . $file->getClientOriginalName());
                $file->move("pdf", $owner->pdf2);
            }
            
            if (Input::hasFile('pdf3') && Input::file('pdf3')->isValid())
            {
                $file = Input::file('pdf3');
                $owner->pdf3 = strtolower('pdf3-' . date('ymdhis') . '-' . $file->getClientOriginalName());
                $file->move("pdf", $owner->pdf3);
            }

            $owner->save();

            return Redirect::route('owner.index')
                            ->with(array('success_msg' => 'Titular afegit correctament'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $owner = Owner::findOrFail($id);
        
        $ownerstall = OwnerStall::where('owner_id', '=', $id)
                ->whereHas('stall', function($q)
                {
                    $q->where('market_id', Session::get('market'));
                })
                ->get();
                
        $presence = Presence::whereHas('ownerstall', function ($q) use($id)
                {
                    $q->whereHas('stall', function($q) use($id)
                            {
                                $q->where('market_id', Session::get('market'));
                            })
                            ->where('owner_id', $id);
                })
                ->with('ownerstall', 'ownerstall.stall', 'calendar')
                ->get();
                
        $notes = Note::whereHas('ownerstall', function ($q) use($id)
                {
                    $q->where('owner_id', $id);
                })
                ->where('market_id', Session::get('market'))
                ->with('ownerstall', 'ownerstall.stall')
                ->get();
        $general = Note::whereNull('ownerstall_id')
                ->where('market_id', Session::get('market'))
                ->with('ownerstall', 'ownerstall.stall')
                ->get();
                
        $absence = Absence::whereHas('ownerstall', function ($q) use($id)
                {
                    $q->whereHas('stall', function($q) use($id)
                            {
                                $q->where('market_id', Session::get('market'));
                            })
                            ->where('owner_id', $id);
                })
                ->with('ownerstall', 'ownerstall.stall')
                ->get();
        
        $invoices = Invoice::whereHas('OwnerStall', function($q) use($id)
                {
                    $q->whereHas('stall', function($q)
                    {
                        $q->where('market_id', Session::get('market'));
                    })
                    ->where('owner_id', $id);
                })
                ->with('ownerstall', 'ownerstall.owner', 'ownerstall.stall')
                ->get();
                
        return View::make('private.owner.show')
                        ->with('owner', $owner)
                        ->with('ownerstalls', $ownerstall)
                        ->with('presence', $presence)
                        ->with('notes', $notes)
                        ->with('general', $general)
                        ->with('absences', $absence)
                        ->with('invoices', $invoices);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        return View::make('private.owner.edit')
                        ->with('owner', Owner::findOrFail($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        $nice = ['name' => 'nom',
                'address' => 'direcció',
                'email' => 'correu electrònic',
                'dni' => 'dni',
                'phone' => 'telèfon',
                'iban' => 'iban',
                'image' => 'foto',
                'pdf1' => 'Alta AIE',
                'pdf2' => 'Alta autònoms',
                'sname' => 'nom del suplent',
                'saddress' => 'direcció del suplent',
                'semail' => 'correu del suplent',
                'sdni' => 'dni del suplent',
                'sphone' => 'teléfon del suplent',
                'pdf3' => 'contracte de treball'];
        
        $owner = Owner::findOrFail($id);

        $inputs = Input::all();
        $rules = [ 'name' => 'required|between:1,100',
            'address' => 'required|between:1,500',
            'email' => 'email|between:1,100',
            'dni' => "required|unique:owner,dni,{$id}|between:9,9",
            'phone' => 'required|digits_between:9,9',
            'iban' => 'required', //think about check it
            'image' => 'image',
            'pdf1' => 'mimes:pdf',
            'pdf2' => 'mimes:pdf',
            'sname' => 'between:1,100',
            'saddress' => 'between:1,500',
            'semail' => 'email|between:1,100',
            'sdni' => 'between:9,9',
            'sphone' => 'digits_between:9,9',
            'pdf3' => 'mimes:pdf'];


        $validation = Validator::make($inputs, $rules);
        $validation->setAttributeNames($nice);

        if ($validation->fails())
        {
            return Redirect::route('owner.edit', array($id))
                            ->withErrors($validation)
                            ->withInput();
        }
        else
        {
            if (Input::hasFile('image') && Input::file('image')->isValid())
            {
                File::delete(public_path() . "assets/imgs/owner/{$owner->image}");

                $file = Input::file('image');
                $owner->image = strtolower('user-' . date('ymdhis') . '-' . $file->getClientOriginalName());
                $file->move("imgs", $owner->image);
            }

            if (Input::hasFile('pdf1') && Input::file('pdf1')->isValid())
            {
                $file = Input::file('pdf1');
                $owner->pdf1 = strtolower('pdf1-' . date('ymdhis') . '-' . $file->getClientOriginalName());
                $file->move("pdf", $owner->pdf1);
            }
            
            if (Input::hasFile('pdf2') && Input::file('pdf2')->isValid())
            {
                $file = Input::file('pdf2');
                $owner->pdf2 = strtolower('pdf2-' . date('ymdhis') . '-' . $file->getClientOriginalName());
                $file->move("pdf", $owner->pdf2);
            }
            
            if (Input::hasFile('pdf3') && Input::file('pdf3')->isValid())
            {

app/views/private/owner/create.blade.php
@include('private.header')

<div class="panel panel-default">
    <div class="panel-heading">
        Afegir titular
    </div>
    <div class="panel-body">

        @include('private.error')

        {{ Form::open(array('route' => "owner.store", 'files' => true, 'class' => 'form-horizontal')) }}

        <h4>Dades del titular</h4>
        
        <div class="form-group">
            <label class="col-sm-3 control-label">Nom</label>
            <div class="col-sm-9">
                {{ Form::text('name', Input::old('name'), Array('class' => 'form-control', 'required', 'autofocus')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Correu electrònic</label>
            <div class="col-sm-9">
                {{ Form::email('email', Input::old('email'), Array('required', 'class' => 'form-control')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">D.N.I.</label>
            <div class="col-sm-9">
                {{ Form::text('dni', Input::old('dni'), Array('class' => 'form-control', 'required')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Direcció</label>
            <div class="col-sm-9">
                {{ Form::text('address', Input::old('address'), Array('class' => 'form-control', 'required')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Telèfon</label>
            <div class="col-sm-9">
                {{ Form::text('phone', Input::old('phone'), Array('class' => 'form-control', 'required')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">IBAN</label>
            <div class="col-sm-9">
                {{ Form::text('iban', Input::old('iban'), Array('class' => 'form-control', 'required')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Foto</label>
            <div class="col-sm-9">
                {{ Form::file('image', Array('class' => 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Alta IAE</label>
            <div class="col-sm-9">
                {{ Form::file('pdf1', Array('class' => 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Alta autònoms</label>
            <div class="col-sm-9">
                {{ Form::file('pdf2', Array('class' => 'form-control')) }}
            </div>
        </div>

        <hr>
        <h4>Dades del suplent</h4>
        <div class="form-group">
            <label class="col-sm-3 control-label">Nom</label>
            <div class="col-sm-9">
                {{ Form::text('sname', Input::old('sname'), Array('class' => 'form-control')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">D.N.I.</label>
            <div class="col-sm-9">
                {{ Form::text('sdni', Input::old('sdni'), Array('class' => 'form-control')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Direcció</label>
            <div class="col-sm-9">
                {{ Form::text('saddress', Input::old('saddress'), Array('class' => 'form-control')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Correu electrònic</label>
            <div class="col-sm-9">
                {{ Form::email('semail', Input::old('semail'), Array('class' => 'form-control')); }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-3 control-label">Telèfon</label>
            <div class="col-sm-9">
                {{ Form::text('sphone', Input::old('sphone'), Array('class' => 'form-control')); }}
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-3 control-label">Contracte</label>
            <div class="col-sm-9">
                {{ Form::file('pdf3', Array('class' => 'form-control')) }}
            </div>
        </div>
        
        <div class="text-right" style="margin-top:50px;">
            <a href="{{ URL::to('owner') }}" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel·lar</a>
            {{ Form::button('<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Guardar', ['class'=>'btn btn-default', 'type'=>'submit']) }}
        </div>

        {{ Form::close() }}
    </div>
</div>

@include('private.footer')

app/views/private/owner/index.blade.php
@include('private.header')

{{ HTML::style('assets/datatables/media/css/dataTables.bootstrap.css'); }}
{{ HTML::style('assets/datatables/extensions/TableTools/css/dataTables.tableTools.min.css'); }}
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                Titulars
            </div>
            <div class="col-md-4 text-right">
                <a href="{{ URL::route('owner.create') }}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Afegir titular
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">

        @include('private.success')
        
        @if ($owners->isEmpty())
        <div class="alert alert-info text-center" role="alert">
            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
            No hi ha titulars
        </div>
        @else
        <table id="datatable" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Nº de parada</th>
                    <th>Nom</th>
                    <th>DNI</th>
                    <th>telefon</th>
                    <th>Correu</th>
                    <th class="text-center">Opcions</th>
                </tr>
            </thead>
            @foreach ($owners as $key => $value)
                  
                   @foreach($value->stalls as $stalls)
  
                         @if($stalls->market_id)

                            <tr>
                                <td>
                                    @foreach ($value->stalls as $stall)
                                        <a href="{{ URL::route('stall.show', $stall->id) }}">{{$stall->num}}</a>
                                    @endforeach
                                </td>
                                <td>{{$value->name}}</td>
                                <td>{{$value->dni}}</td>
                                <td>{{$value->phone}}</td>
                                <td>{{$value->email}}</td>
                                <td class="text-center">
                                    <a class='btn btn-default btn-xs ttip' data-toggle="tooltip" data-placement="top" title="Veure fitxa" href="{{ URL::route('owner.show', $value->id) }}">
                                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                    </a>
                                    <a class='btn btn-default btn-xs ttip' data-toggle="tooltip" data-placement="top" title="Asignar parada" href="{{ URL::route('ownerstall.create', ['owner_id' => $value->id]) }}">
                                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                    </a>
                                    <a class='btn btn-default btn-xs ttip' data-toggle="tooltip" data-placement="top" title="Editar titular" href="{{ URL::route('owner.edit', $value->id) }}">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                </td>
                            </tr>

                        @endif

                    @endforeach

            @endforeach
        </table>
        @endif
    </div>
</div>

@include('private.footer')

{{ HTML::script('assets/datatables/media/js/jquery.dataTables.js'); }}
{{ HTML::script('assets/datatables/media/js/dataTables.bootstrap.js'); }}
{{ HTML::script('assets/datatables/media/js/Spanish.js'); }}
{{ HTML::script('assets/datatables/extensions/dataTables.tableTools.min.js')}}

<script>
    $(document).ready(function () {
        $('#datatable').DataTable({
            dom: 'lTfrtip',
            language: spanish,
            columnDefs: [{orderable: false, targets: [3]}],
            tableTools: {
                    sSwfPath: "{{ URL::asset('assets/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf') }}",
                    aButtons: [
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'print',
                            sButtonText: 'Imprimir',
                            sInfo: "<h4>Utilitzi el menú de l'explorador per imprimir la página</h4>Premi [Esc] per sortir"
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'xls',
                            sFileName: "*.xls",
                            sButtonText: 'XLS'
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'csv',
                            sButtonText: 'CSV'
                        }
                    ]
            }
        });
    });
</script>