app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Display all SQL executed in Eloquent 
/*Event::listen('illuminate.query', function($query)
{
    var_dump($query);
});*/

// canviar pass admin
Route::get('crearpass_admin', function()
{
    DB::table('users')
            ->where('id', 10)
            ->update(array('password' => Hash::make('UFdn24XTY')));
});



Route::get('login', 'AuthController@getLogIn');

Route::post('login', 'AuthController@postLogIn');

Route::controller('password', 'RemindersController');


//Invoice test (Rebuts)
Route::post('print/invoice/print', ['as' => 'invoice.payprintapp', 'uses' => 'InvoiceController@payprintapp']);
Route::get('print/invoice/print', ['as' => 'invoice.payprintapp', 'uses' => 'InvoiceController@payprintapp']);



Route::group(array('before' => 'auth'), function()
{
    Route::get('error', function(){
        return View::make('private.modelexception'); 
    });



    Route::get('/', 'HomeController@home');
    
    Route::get('logout', 'AuthController@postLogOut');

    Route::get('move/{id}', 'AuthController@move');

    Route::get('stall/getinfo', 'StallController@getInfo');

    Route::get('stall/ajaxSearch', 'StallController@ajaxSearch');

    Route::any('mapa', 'MapController@showMap');

    Route::post('presence/toggle', 'PresenceController@togglePresence');

    Route::post('sector/editProducts/{id}', 'SectorController@editProducts');
    Route::post('sector/deleteProducts/{id}', 'SectorController@deleteProducts');


    
    //ADMIN
    Route::group(array('before' => 'admin'), function()
    {
        Route::resource('user', 'UserController');
        Route::get('stall/{id}', 'StallController@show');
        Route::get('stall/{id}/edit', 'StallController@editStall');


        

    });
    
    // INT
    Route::group(array('before' => 'int'), function()
    {
        Route::get('ownerstall/ajaxStallSearch', 'OwnerStallController@ajaxStallSearch');
        Route::get('ownerstall/ajaxOwnerSearch', 'OwnerStallController@ajaxOwnerSearch');
        Route::resource('ownerstall', 'OwnerStallController');

        Route::resource('sector', 'SectorController');

        Route::resource('authprod', 'AuthProdController');

        Route::resource('calendar', 'CalendarController');

        Route::resource('absence', 'AbsenceController');

        Route::resource('tariff', 'TariffController');
    });
    
    // TAB
    Route::group(array('before' => 'tab'), function()
    {
        // OWNER
        Route::get('owner/ajaxSearch', 'OwnerController@ajaxSearch');
        Route::resource('owner', 'OwnerController');
        
        // STALL
/*        Route::get('stall/ajaxSearch', 'StallController@ajaxSearch2');
*/        Route::resource('stall', 'StallController');
        
        // INVOICE
        Route::get('invoice/printout/{id}', ['as' => 'invoice.printout', 'uses' => 'InvoiceController@printout']);
        Route::get('invoice/payprint/{id}', ['as' => 'invoice.payprint', 'uses' => 'InvoiceController@payprint']);
        Route::resource('invoice', 'InvoiceController');
        Route::get('invoice/printandpay/{id}',['as' => 'invoice.printandpay', 'uses' => 'InvoiceController@printandpay']);
        Route::get('notpaid', ['as' => 'invoice.notpaid', 'uses' => 'InvoiceController@indexNotPaid']);

        // PRESENCE
        Route::resource('presence', 'PresenceController');
        Route::get('presence_no',   'PresenceController@indexPresence');

        // NOTES
        Route::resource('notes', 'NotesController');

        // AUTHPROD
        Route::get('authprod/sector/{id}',['as' => 'authprod.showsector', 'uses' => 'AuthProdController@relation_sector_products']);

    });

    
    
});

app/models/Calendar.php
<?php

class Calendar extends Eloquent
{

    protected $table = 'calendar';
    protected $fillable = array('date');

    public function getDateAttribute($value)
    {
        return date("d-m-Y", strtotime($value));
    }
    
        
    public function setDateAttribute($value)
    {
        $this->attributes['date'] = date('Y-m-d', strtotime($value));
    }
    
//    public function setDateAttribute($value)
//    {
//        $this->attributes['date'] = date('Y-m-d', strtotime($value));
//    }
}

app/controllers/CalendarController.php
<?php

use Carbon\Carbon;

class CalendarController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $days = Calendar::where('market_id', '=', Session::get('market'))->get();

        if (Input::get('view') == 'calendar')
            return View::make('private.calendar.index-calendar')
                            ->with('days', $days);
        else
            return View::make('private.calendar.index-list')
                            ->with('days', $days);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('private.calendar.create')
                        ->with('daysofweek', ['Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte','Diumenge']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */

    public function store()
    {
        
        $inputs = Input::all();
        $rules = [ 'days' => 'required|array']; //max length?
        
        foreach ((array) Input::get('days') as $key => $value)
        {
            $rules["day-{$key}"] = "date|unique_composite:calendar,date,market_id," . Session::get('market'); //custom validation: both market_id and date = unique
            $inputs["day-{$key}"] = date('Y-m-d', strtotime($value)) . ' 00:00:00';
            $niceName["day-{$key}"] = "data {$value}";
        }

        $validation = Validator::make($inputs, $rules);
        $validation->setAttributeNames($niceName); 


        if ($validation->fails())
        {
            return Redirect::route('calendar.create')
                            ->withErrors($validation)
                            ->withInput();
        }
        else
        {
            foreach (Input::get('days') as $value)
            {
                $calendar = new Calendar();
                $calendar->date = $value;
                $calendar->market_id = Session::get('market');
                $calendar->save();
            }
            return Redirect::route('calendar.index')
                            ->with(array('success_msg' => 'Datas afegides correctament.'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $day = Calendar::findOrFail($id);

        $presence = OwnerStall::whereHas('stall', function($q) {
                            $q->where('market_id', Session::get('market'));
                        })
                        ->whereHas('presence', function($q) use ($id) {
                            $q->where('calendar_id', $id);
                        })
                        ->with('presence')
                        ->with('owner')
                        ->with('stall')
                        ->get();

        $missing = [];
//        $missing = OwnerStall::where('deactivated_at', null)
//                        ->whereHas('stall', function($q) {
//                            $q->where('market_id', Session::get('market'));
//                        })
//                        ->whereHas('presence', function($q) use ($id) {
//                            $q->where('calendar_id', $id);
//                        }, 0)
//                        ->with('presence')
//                        ->with('owner')
//                        ->with('stall')
//                        ->get();
          
        $general = Note::where('calendar_id', $id)
                        ->whereNull('ownerstall_id')
                        ->where('market_id', Session::get('market'))
                        ->get();
        
        $notes = Note::where('calendar_id', $id)
                        ->whereNotNull('ownerstall_id')
                        ->where('market_id', Session::get('market'))
                        ->with('ownerstall', 'ownerstall.owner', 'ownerstall.stall')
                        ->get();
        
        $absences = Absence::whereRaw("'".date("Y-m-d", strtotime($day->date))."' between `start_at` and `end_at`")
                            ->whereHas('ownerstall', function($q) {
                            $q->whereHas('stall', function($q){
                                $q->where('market_id', Session::get('market'));
                            });
                        })
                        ->with('ownerstall', 'ownerstall.owner', 'ownerstall.stall')
                        ->get();
                        
        return View::make('private.calendar.show')
                        ->with('day', $day)
                        ->with('presence', $presence)
                        ->with('missing', $missing)
                        ->with('general', $general)
                        ->with('notes', $notes)
                        ->with('absences', $absences);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $date = Calendar::where('market_id', Session::get('market'))->findOrFail($id);
        try 
        {
            $date->delete();
            
            return Redirect::route('calendar.index')
                ->with(array('success_msg' => 'Data eliminada correctament.'));
        } 
        catch ( Illuminate\Database\QueryException $e) 
        {
            return Redirect::route('calendar.index')
                ->with(array('error_msg' => 'No es pot eliminar la data.'));
        }
    }

}

app/views/private/calendar/create.blade.php
@include('private.header')


<div class="panel panel-default">
    <div class="panel-heading">
        Afegir dies al calendari
    </div>
    <div class="panel-body">

        @include('private.error')

        {{ Form::open(array('route' => "calendar.store", 'class' => 'form-horizontal')) }}
        <div class="row">
            <div class="col-md-7">
                <div class="form-group">
                    <label class="col-sm-3 control-label">Tot el mes</label>
                    <div class="col-sm-9">
                        <div class="input-group">
                            {{ Form::input('month', 'month', null, Array('class' => 'form-control', 'id' => 'input-month')); }}
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button" id="btn-month">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                        <p class="help-block">S'afegiran tots els <b>{{$daysofweek[($cMarket->dayofweek - 1)]}}</b> del mes.</p>
                        <p class="help-block">Recordeu apretar el botó <b>+</b> per tal de fer efectiu l'entrada.</p>

                    </div>
                </div>
                <hr>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Un dia</label>
                    <div class="col-sm-9">
                        <div class="input-group">
                            {{ Form::input('date', 'date', null, Array('class' => 'form-control', 'id' => 'input-date')); }}
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button" id="btn-day">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                        <p class="help-block">Recordeu apretar el botó <b>+</b> per tal de fer efectiu l'entrada.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-5 div-dates">
                @foreach ((array)Input::old('days') as $value)
                    <div class="alert alert-info alert-dismissible text-center" role="alert"> 
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> 
                    <p>Data per afegir: {{$value}}</p> 
                    <input type="hidden" name="days[]" value="{{$value}}"> 
                    </div>
                @endforeach
            </div>
        </div>

        <div class="text-right" style="margin-top:50px;">
            <a href="{{ URL::to('calendar') }}" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel·lar</a>
            {{ Form::button('<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Guardar', ['class'=>'btn btn-default', 'type'=>'submit']) }}
        </div>

        {{ Form::close() }}
    </div>
</div>

@include('private.footer')

<script>
    var dayofweek = <?= $cMarket->dayofweek ?>; 
    var days;

    function getDays(str, day) {
        var d = new Date(str);
        month = d.getMonth();
        days = [];
        d.setDate(1);
        
        while (d.getDay() !== day) {
            d.setDate(d.getDate() + 1);
        }

        while (d.getMonth() === month) {
            days.push(new Date(d.getTime()));
            d.setDate(d.getDate() + 7);
        }
        
        return days;
    }
    
    $('document').ready(function () {


        $('#btn-month').click(function () {
            getDays($('#input-month').val() + '-01', dayofweek).forEach(function (date) {

                var strdate = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
                if ($( "[value='" + strdate + "']" ).length === 0)
                {
                    var str = '<div class="alert alert-info alert-dismissible text-center" role="alert">' +
                            '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>' +
                            '<p>Fecha para añadir: ' + strdate + '</p>' +
                            '<input type="hidden" name="days[]" value="' + strdate + '">' +
                            '</div>';
                    $('.div-dates').append(str);
                }
            });
        });
        
        $('#btn-day').click(function () {
                var date = new Date($('#input-date').val());
                var strdate = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
                
                if ($( "[value='" + strdate + "']" ).length === 0 && !isNaN(date.getDate()))
                {
                    var str = '<div class="alert alert-info alert-dismissible text-center" role="alert">' +
                            '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>' +
                            '<p>Fecha para añadir: ' + strdate + '</p>' +
                            '<input id="strdate" type="hidden" name="days[]" value="' + strdate + '">' +
                            '</div>';
                    $('.div-dates').append(str);
                }
                else alert('La data no és vàlida');

        });

          $('form').on('submit', function(e){
            var day_u = '';
            day_u = $('#strdate').val()
            console.log(day_u);
            
            if(!days) {
                if(!day_u){
                    e.preventDefault();
                    alert ('No hi ha cap data afegida, al seleccionar data recordi apretar el botó "+"');
                }
            }
          });
    });
</script>

app/views/private/calendar/index-calendar.blade.php
@include('private.header')

{{ HTML::style('assets/datatables/media/css/dataTables.bootstrap.css'); }}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-4">
                Calendari
            </div>
            <div class='col-md-4 text-center'>
                <div class="btn-group" role="group">
                    <a href="{{ URL::route('calendar.index', ['view' => 'calendar']) }}" class="btn btn-default btn-xs active">Veure calendari</a>
                    <a href="{{ URL::route('calendar.index', ['view' => 'list']) }}" class="btn btn-default btn-xs">Veure llistat</a>
                </div>
            </div>
            <div class="col-md-4 text-right">
                <a href="{{ URL::route('calendar.create') }}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Afegir dies
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        @include('private.success')

        <div id="calendar"></div>

    </div>
</div>


<div class="modal fade">
  
</div>

@include('private.footer')

{{ HTML::script('assets/underscore-min.js'); }}
{{ HTML::script('assets/clndr/example/moment-2.8.3.js'); }}
{{ HTML::script('assets/clndr/src/clndr.js'); }}


{{ HTML::script('assets/datatables/media/js/jquery.dataTables.js'); }}
{{ HTML::script('assets/datatables/media/js/dataTables.bootstrap.js'); }}
{{ HTML::script('assets/datatables/media/js/Spanish.js'); }}

<script type="text/template" id='calendar-template'>
    <div class="row">
    <div class="col-md-4">
    <button class="btn btn-default clndr-previous-button">&lsaquo;</button>
    </div>
    <div class="col-md-4 text-center"><%= month %> <%= year %></div>
    <div class="col-md-4 text-right">
    <button class="btn btn-default clndr-next-button">&rsaquo;</button>
    </div>
    </div>

    <div class="clndr-grid">
    <div class="row">
    <% _.each(daysOfTheWeek, function(day) { %>
    <div class="calendar-title"><%= day %></div>
    <% }); %>
    </div>

    <div class="days row">
    <% _.each(days, function(day) {  %>
    <div class="<%= day.classes %>">
        <%= day.day %>
    </div>
    <% }); %>
    </div>

    </div>
    </div>
</script>

<style>
    .today{
        color: #3c763d;
        background-color: #dff0d8;
        border-color: #d6e9c6;
    }
    .event
    {
        color: #31708f;
        background-color: #d9edf7;
        border-color: #bce8f1;
        cursor:pointer;
    }
    .calendar-title
    {
        width: 14.28%;
        float: left;
        padding: 5px;
        border:1px solid #ddd;
        text-align:center;
        padding:20px;
        background-color: #f5f5f5;
    }

    .calendar-dow-0, .calendar-dow-1, .calendar-dow-2, .calendar-dow-3,
    .calendar-dow-4, .calendar-dow-5, .calendar-dow-6
    {
        width: 14.28%;
        float: left;
        border:1px solid #ddd;
        text-align:center;
        padding:20px;
    }

    .calendar-dow-0:hover, .calendar-dow-1:hover, .calendar-dow-2:hover, .calendar-dow-3:hover,
    .calendar-dow-4:hover, .calendar-dow-5:hover, .calendar-dow-6:hover
    {
        background-color: #f5f5f5;
    }

    .clndr-grid
    {
        margin:50px;
    }

</style>
<script>
    $(document).ready(function () {
        
        $('#calendar').clndr({
            showAdjacentMonths: true,
            adjacentDaysChangeMonth: false,
            startWithMonth: moment(),
            template: $('#calendar-template').html(),
            weekOffset: 1,
            daysOfTheWeek: ['Diumenge', 'Dilluns', 'Dimarts', 'Dimecres', 'Dijous', 'Divendres', 'Dissabte'],
            events: [
                @foreach ($days as $value)
                { date: "<?=date('Y-m-d', strtotime($value->date))?>", title: "Mercat", url: "<?=URL::route('calendar.show', $value->id)?>" },
                @endforeach
            ],
            clickEvents: {
                click: function (target) {
                    $.ajax({
                        type: "get",
                        url: target.events[0].url
                      })
                        .done(function( msg ) {
                            $('.modal').html(msg);
                            $('.modal').modal('show');
                    });
                }
            }
        });
    });
</script>

app/views/private/calendar/index-list.blade.php
@include('private.header')

{{ HTML::style('assets/datatables/media/css/dataTables.bootstrap.css'); }}
{{ HTML::style('assets/datatables/extensions/TableTools/css/dataTables.tableTools.min.css'); }}
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-4">
                Calendari
            </div>
            <div class='col-md-4 text-center'>
                <div class="btn-group" role="group">
                    <a href="{{ URL::route('calendar.index', ['view' => 'calendar']) }}" class="btn btn-default btn-xs">Veure calendari</a>
                    <a href="{{ URL::route('calendar.index', ['view' => 'list']) }}" class="btn btn-default btn-xs active">Veure llistat</a>
                </div>
            </div>
            <div class="col-md-4 text-right">
                <a href="{{ URL::route('calendar.create') }}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Afegir dies
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        @include('private.success')

        @if ($days->isEmpty())
        <div class="alert alert-info text-center" role="alert">
            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
            No hi ha dies
        </div>
        @else
        <table id="datatable" class="table table-striped table-hover table-condensed">
            <thead>
                <tr>
                    <th>Día</th>
                    <th class="text-center">Opcions</th>
                </tr>
            </thead>
            @foreach ($days as $value)
            <tr>
                <td data-order='{{strtotime($value->date)}}'>{{date('d-m-Y', strtotime($value->date))}}</td>
                <td class="text-center">
                    {{ Form::open(array('url' => "calendar/{$value->id}")) }}
                    <a class="btn btn-default btn-xs show-modal ttip" data-toggle="tooltip" data-placement="top" title="Veure resum" data-url="{{ URL::route("calendar.show", $value->id)}}">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    </a>
                    <a class="btn btn-default btn-xs ttip" data-toggle="tooltip" data-placement="top" title="Afegir assistència" href="{{ URL::route("presence.create", ['calendar_id' => $value->id])}}">
                        <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
                    </a>
                    <a class="btn btn-default btn-xs ttip" data-toggle="tooltip" data-placement="top" title="Afegir incidència" href="{{ URL::route("notes.create", ['calendar_id' => $value->id])}}">
                        <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                    </a>
                    {{ Form::hidden('_method', 'DELETE') }}
                    {{ Form::button('<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>', ['class'=>'btn  btn-xs btn-danger confirm ttip', 'data-toggle'=>"tooltip", 'data-placement'=>"top", 'title'=>"Eliminar día", 'type'=>'submit']) }}
                    {{ Form::close() }}
                </td>
            </tr>
            @endforeach
        </table>
        @endif
    </div>
</div>



<div class="modal fade">

</div>

@include('private.footer')

{{ HTML::script('assets/datatables/media/js/jquery.dataTables.js'); }}
{{ HTML::script('assets/datatables/media/js/dataTables.bootstrap.js'); }}
{{ HTML::script('assets/datatables/media/js/Spanish.js'); }}
{{ HTML::script('assets/datatables/extensions/dataTables.tableTools.min.js')}}

<script>
    $('.show-modal').click(function () {
        $.ajax({
            type: "get",
            url: $(this).data('url')
        }).done(function (msg) {
            $('.modal').html(msg);
            $('.modal').modal('show');
        });
    });
    
    $('.confirm').click(function () {
        if (confirm("Desitja eliminar la data?") === false)
        {
            event.preventDefault();
            return false;
        }
    });

    $(document).ready(function () {

        $('#datatable').DataTable({
            dom: 'lTfrtip',
            language: spanish,
            tableTools: {
                    sSwfPath: "{{ URL::asset('assets/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf') }}",
                    aButtons: [
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'print',
                            sButtonText: 'Imprimir',
                            sInfo: "<h4>Utilitzi el menú de l'explorador per imprimir la página</h4>Premi [Esc] per sortir"
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'xls',
                            sFileName: "*.xls",
                            sButtonText: 'XLS'
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'csv',
                            sButtonText: 'CSV'
                        }
                    ]
            }
        });
    });
</script>