app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// Display all SQL executed in Eloquent 
/*Event::listen('illuminate.query', function($query)
{
    var_dump($query);
});*/

// canviar pass admin
Route::get('crearpass_admin', function()
{
    DB::table('users')
            ->where('id', 10)
            ->update(array('password' => Hash::make('UFdn24XTY')));
});



Route::get('login', 'AuthController@getLogIn');

Route::post('login', 'AuthController@postLogIn');

Route::controller('password', 'RemindersController');


//Invoice test (Rebuts)
Route::post('print/invoice/print', ['as' => 'invoice.payprintapp', 'uses' => 'InvoiceController@payprintapp']);
Route::get('print/invoice/print', ['as' => 'invoice.payprintapp', 'uses' => 'InvoiceController@payprintapp']);



Route::group(array('before' => 'auth'), function()
{
    Route::get('error', function(){
        return View::make('private.modelexception'); 
    });



    Route::get('/', 'HomeController@home');
    
    Route::get('logout', 'AuthController@postLogOut');

    Route::get('move/{id}', 'AuthController@move');

    Route::get('stall/getinfo', 'StallController@getInfo');

    Route::get('stall/ajaxSearch', 'StallController@ajaxSearch');

    Route::any('mapa', 'MapController@showMap');

    Route::post('presence/toggle', 'PresenceController@togglePresence');

    Route::post('sector/editProducts/{id}', 'SectorController@editProducts');
    Route::post('sector/deleteProducts/{id}', 'SectorController@deleteProducts');


    
    //ADMIN
    Route::group(array('before' => 'admin'), function()
    {
        Route::resource('user', 'UserController');
        Route::get('stall/{id}', 'StallController@show');
        Route::get('stall/{id}/edit', 'StallController@editStall');


        

    });
    
    // INT
    Route::group(array('before' => 'int'), function()
    {
        Route::get('ownerstall/ajaxStallSearch', 'OwnerStallController@ajaxStallSearch');
        Route::get('ownerstall/ajaxOwnerSearch', 'OwnerStallController@ajaxOwnerSearch');
        Route::resource('ownerstall', 'OwnerStallController');

        Route::resource('sector', 'SectorController');

        Route::resource('authprod', 'AuthProdController');

        Route::resource('calendar', 'CalendarController');

        Route::resource('absence', 'AbsenceController');

        Route::resource('tariff', 'TariffController');
    });
    
    // TAB
    Route::group(array('before' => 'tab'), function()
    {
        // OWNER
        Route::get('owner/ajaxSearch', 'OwnerController@ajaxSearch');
        Route::resource('owner', 'OwnerController');
        
        // STALL
/*        Route::get('stall/ajaxSearch', 'StallController@ajaxSearch2');
*/        Route::resource('stall', 'StallController');
        
        // INVOICE
        Route::get('invoice/printout/{id}', ['as' => 'invoice.printout', 'uses' => 'InvoiceController@printout']);
        Route::get('invoice/payprint/{id}', ['as' => 'invoice.payprint', 'uses' => 'InvoiceController@payprint']);
        Route::resource('invoice', 'InvoiceController');
        Route::get('invoice/printandpay/{id}',['as' => 'invoice.printandpay', 'uses' => 'InvoiceController@printandpay']);
        Route::get('notpaid', ['as' => 'invoice.notpaid', 'uses' => 'InvoiceController@indexNotPaid']);

        // PRESENCE
        Route::resource('presence', 'PresenceController');
        Route::get('presence_no',   'PresenceController@indexPresence');

        // NOTES
        Route::resource('notes', 'NotesController');

        // AUTHPROD
        Route::get('authprod/sector/{id}',['as' => 'authprod.showsector', 'uses' => 'AuthProdController@relation_sector_products']);

    });

    
    
});

app/models/AuthProd.php
<?php

class AuthProd extends Eloquent
{

    protected $table = 'auth_prod';
    protected $fillable = array('name');
}

app/controllers/AuthProdController.php
<?php

class AuthProdController extends \BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $authprod = AuthProd::where('market_id', Session::get('market'))->get();
        
        return View::make('private.authprod.index')
                        ->with('authprods', $authprod);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('private.authprod.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $validation = Validator::make(Input::all(), ['name' => 'required']);

        if ($validation->fails())
        {
            return Redirect::route('authprod.create')
                            ->withErrors($validation)
                            ->withInput();
        }
        else
        {
            $authprod = new AuthProd(Input::all());
            $authprod->market_id = Session::get('market');
            $authprod->save();

            return Redirect::route('authprod.index')
                            ->with(array('success_msg' => 'Producte autoritzat afegit correctament'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {

        $sectors = DB::table('sector')->lists('name','id');

        $rel_prod_sectors = DB::table('rel_prod_sectors')
                                    ->where('id_product', $id)->select('id_sector')->get();

        return View::make('private.authprod.show')
                        ->with('products',$rel_prod_sectors)
                        ->with('sectors',$sectors);


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $authprod = AuthProd::where('market_id', Session::get('market'))->findOrFail($id);
        
        return View::make('private.authprod.edit')
                        ->with('authprod', $authprod);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {
        $authprod = AuthProd::where('market_id', Session::get('market'))->findOrFail($id);
        
        $validation = Validator::make(Input::all(), ['name' => 'required']);

        if ($validation->fails())
        {
            return Redirect::route('authprod.edit')
                            ->withErrors($validation)
                            ->withInput();
        }
        else
        {
            $authprod->market_id = Session::get('market');
            $authprod->update(Input::all());

            return Redirect::route('authprod.index')
                            ->with(array('success_msg' => 'Producte autoritzat editat correctament.'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $authprod = AuthProd::where('market_id', Session::get('market'))->findOrFail($id);

        if (Stall::where('auth_prod_id', $id)->count() > 0)
        {
              return Redirect::route('authprod.index')
                ->with(array('error_msg' => 'No es pot eliminar el producte autoritzat.'));
        }
        else 
        {
            $authprod->delete();
            return Redirect::route('authprod.index')
                ->with(array('success_msg' => 'Producte autoritzat eliminat correctament.'));
        }
    }


    /**
     * Show relation with sectors and auth products.
     *
     * @param  int  $id
     * @return Response
     */
    public function relation_sector_products($id)
    {

        $authprod   = DB::table('auth_prod')->where('id', $id)->first();

        $stalls     = DB::table('stall')->lists('sector_id','id');
        $rel_prod   = DB::table('rel_prod_sectors')->where('id_product', $id)->get();

        return View::make('private.authprod.showsectors')->with('stalls',$stalls)
                                                         ->with('rel_prod',$rel_prod)
                                                         ->with('authprod',$authprod);
        
    }


}

app/views/private/authprod/create.blade.php
@include('private.header')

<div class="panel panel-default">
    <div class="panel-heading">
        Afegir producte autoritzat
    </div>
    <div class="panel-body">

        @include('private.error')

        {{ Form::open(array('route' => "authprod.store", 'class' => 'form-horizontal')) }}

        <div class="form-group">
            <label class="col-sm-3 control-label">Nom</label>
            <div class="col-sm-9">
                {{ Form::text('name', Input::old('name'), Array('class' => 'form-control', 'required', 'autofocus')); }}
            </div>
        </div>

        <div class="text-right" style="margin-top:50px;">
            <a href="{{ URL::to('authprod') }}" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel·lar</a>
            {{ Form::button('<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Guardar', ['class'=>'btn btn-default', 'type'=>'submit']) }}
        </div>

        {{ Form::close() }}
    </div>
</div>

@include('private.footer')

app/views/private/authprod/edit.blade.php
@include('private.header')

<div class="panel panel-default">
    <div class="panel-heading">
        Editar producte autoritzat
    </div>
    <div class="panel-body">

        @include('private.error')

        {{ Form::model($authprod, array('route' => array('authprod.update', $authprod->id), 'method' => 'PUT', 'class' => 'form-horizontal')) }}

        <div class="form-group">
            <label class="col-sm-3 control-label">Nom</label>
            <div class="col-sm-9">
                {{ Form::text('name', Input::old('name'), Array('class' => 'form-control', 'required', 'autofocus')); }}
            </div>
        </div>

        <div class="text-right" style="margin-top:50px;">
            <a href="{{ URL::to('authprod') }}" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel·lar</a>
            {{ Form::button('<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Guardar', ['class'=>'btn btn-default', 'type'=>'submit']) }}
        </div>

        {{ Form::close() }}
    </div>
</div>

@include('private.footer')

app/views/private/authprod/index.blade.php
@include('private.header')

{{ HTML::style('assets/datatables/media/css/dataTables.bootstrap.css'); }}
{{ HTML::style('assets/datatables/extensions/TableTools/css/dataTables.tableTools.min.css'); }}
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                Productes autoritzats
            </div>
            <div class="col-md-4 text-right">
                <a href="{{ URL::route('authprod.create') }}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Afegir
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        @include('private.success')

        @if ($authprods->isEmpty())
        <div class="alert alert-info text-center" role="alert">
            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
            No hi ha productes autoritzats
        </div>
        @else
        <table id="datatable" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th class="text-center">Editar</th>
                </tr>
            </thead>
            @foreach ($authprods as $key => $value)
            <tr>
                <td>{{$value->name}}</td>
                <td class="text-center">
                    {{ Form::open(array('url' => "authprod/{$value->id}")) }}
                    <a class='btn btn-default btn-xs' data-toggle="tooltip" data-placement="top" title="Editar producte" href="{{ URL::route('authprod.edit', $value->id) }}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>
                    <a class='btn btn-default btn-xs' data-toggle="tooltip" data-placement="top" title="Veure fitxa" href="{{ URL::route('authprod.show', $value->id) }}">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    </a>
                    <a class='btn btn-default btn-xs' data-toggle="tooltip" data-placement="top" title="Parades Asignades" href="{{ URL::route('authprod.showsector', $value->id) }}">
                        <span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>
                    </a>
                    {{ Form::hidden('_method', 'DELETE') }}
                    {{ Form::button('<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>', ['class'=>'btn  btn-xs btn-danger confirm', 'data-toggle'=>"tooltip", 'data-placement'=>"top", 'title'=>"Eliminar producte", 'type'=>'submit']) }}
                    {{ Form::close() }}
                </td>
            </tr>
            @endforeach
        </table>
        @endif
    </div>
</div>

@include('private.footer')

{{ HTML::script('assets/datatables/media/js/jquery.dataTables.js'); }}
{{ HTML::script('assets/datatables/media/js/dataTables.bootstrap.js'); }}
{{ HTML::script('assets/datatables/media/js/Spanish.js'); }}
{{ HTML::script('assets/datatables/extensions/dataTables.tableTools.min.js')}}

<script>
    $('.confirm').click(function () {
        if (confirm("Desitja eliminar el producte autoritzat?") === false)
        {
            event.preventDefault();
            return false;
        }
    });

    $(document).ready(function () {
        $('#datatable').DataTable({
            dom: 'lTfrtip',
            language: spanish,
            columnDefs: [{orderable: false, targets: [1]}],
            tableTools: {
                    sSwfPath: "{{ URL::asset('assets/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf') }}",
                    aButtons: [
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'print',
                            sButtonText: 'Imprimir',
                            sInfo: "<h4>Utilitzi el menú de l'explorador per imprimir la página</h4>Premi [Esc] per sortir"
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'xls',
                            sFileName: "*.xls",
                            sButtonText: 'XLS'
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'csv',
                            sButtonText: 'CSV'
                        }
                    ]
            }
        });
    });
</script>

app/views/private/authprod/show.blade.php
@include('private.header')

{{ HTML::style('assets/datatables/media/css/dataTables.bootstrap.css'); }}
{{ HTML::style('assets/datatables/extensions/TableTools/css/dataTables.tableTools.min.css'); }}
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                Sectors del producte autoritzat
            </div>
            <div class="col-md-4 text-right">
            </div>
        </div>
    </div>
    <div class="panel-body">
        @include('private.success')

        <table id="datatable" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th class="text-center">Veure Sector</th>
                </tr>
            </thead>
            @foreach ($products as $key => $value)
            <tr>
                <td>{{$sectors[$value->id_sector]}}</td>
                <td class="text-center">
                    <a class='btn btn-default btn-xs' data-toggle="tooltip" data-placement="top" title="Veure fitxa" href="{{ URL::route('sector.show', $value->id_sector) }}">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    </a>
                
                </td>
            </tr>
            @endforeach
        </table>
    </div>
</div>

@include('private.footer')

{{ HTML::script('assets/datatables/media/js/jquery.dataTables.js'); }}
{{ HTML::script('assets/datatables/media/js/dataTables.bootstrap.js'); }}
{{ HTML::script('assets/datatables/media/js/Spanish.js'); }}
{{ HTML::script('assets/datatables/extensions/dataTables.tableTools.min.js')}}

<script>
    $('.confirm').click(function () {
        if (confirm("Desitja eliminar el producte autoritzat?") === false)
        {
            event.preventDefault();
            return false;
        }
    });

    $(document).ready(function () {
        $('#datatable').DataTable({
            dom: 'lTfrtip',
            language: spanish,
            columnDefs: [{orderable: false, targets: [1]}],
            tableTools: {
                    sSwfPath: "{{ URL::asset('assets/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf') }}",
                    aButtons: [
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'print',
                            sButtonText: 'Imprimir',
                            sInfo: "<h4>Utilitzi el menú de l'explorador per imprimir la página</h4>Premi [Esc] per sortir"
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'xls',
                            sFileName: "*.xls",
                            sButtonText: 'XLS'
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'csv',
                            sButtonText: 'CSV'
                        }
                    ]
            }
        });
    });
</script>

app/views/private/authprod/showsectors.blade.php
@include('private.header')

{{ HTML::style('assets/datatables/media/css/dataTables.bootstrap.css'); }}
{{ HTML::style('assets/datatables/extensions/TableTools/css/dataTables.tableTools.min.css'); }}


<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                Parades que inclouen el producte autoritzat : <b>{{$authprod->name}}</b>
            </div>
            <div class="col-md-4 text-right">
            </div>
        </div>
    </div>
    <div class="panel-body">
        @include('private.success')

        <table id="datatable" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Numero de parada</th>
                    <th class="text-center">Veure parada</th>
                </tr>
            </thead>
            @foreach ($stalls as $stall => $sector)
                
                @foreach ($rel_prod as $key => $value)
   
                    @if ($value->id_sector == $sector)   
                        <tr>
                            <td>Nº de parada : {{$stall}}</td>
                            <td class="text-center">
                                <a class='btn btn-default btn-xs' data-toggle="tooltip" data-placement="top" title="Veure fitxa" href="{{ URL::route('stall.show', $stall) }}">
                                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                </a>
                            
                            </td>
                        </tr>
                    @endif
                
                @endforeach

            @endforeach
        </table>
    </div>
</div>

@include('private.footer')

{{ HTML::script('assets/datatables/media/js/jquery.dataTables.js'); }}
{{ HTML::script('assets/datatables/media/js/dataTables.bootstrap.js'); }}
{{ HTML::script('assets/datatables/media/js/Spanish.js'); }}
{{ HTML::script('assets/datatables/extensions/dataTables.tableTools.min.js')}}

<script>
    $('.confirm').click(function () {
        if (confirm("Desitja eliminar el producte autoritzat?") === false)
        {
            event.preventDefault();
            return false;
        }
    });

    $(document).ready(function () {
        $('#datatable').DataTable({
            dom: 'lTfrtip',
            language: spanish,
            columnDefs: [{orderable: false, targets: [1]}],
            tableTools: {
                    sSwfPath: "{{ URL::asset('assets/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf') }}",
                    aButtons: [
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'print',
                            sButtonText: 'Imprimir',
                            sInfo: "<h4>Utilitzi el menú de l'explorador per imprimir la página</h4>Premi [Esc] per sortir"
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'xls',
                            sFileName: "*.xls",
                            sButtonText: 'XLS'
                        },
                        {
                            oSelectorOpts: { filter: 'applied', order: 'current' },
                            sExtends: 'csv',
                            sButtonText: 'CSV'
                        }
                    ]
            }
        });
    });
</script>